### ISSUE TITLE
[PE-D] Checking for duplicate persons does not consider if there is already an edited version before

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-3/tp#140]
HOW TO REPLICATE
1. ```add n/Test```
2. ```edit 1 d/fjfaskjfalhfjas```
3. ```add n/Test```

**EXPECTED**: ```This person already exists in the address book```

**ACTUAL**: ```New person added: Test; Phone: -; Email: -; LinkedIn: -; Github: -; Detail: ```

![Screenshot 2021-10-29 at 4.48.13 PM.png](https://raw.githubusercontent.com/didymental/ped/main/files/1df2882a-70b7-46d7-9844-398259b556e7.png)

![Screenshot 2021-10-29 at 4.48.22 PM.png](https://raw.githubusercontent.com/didymental/ped/main/files/ab517bc3-f219-4fb8-aa6f-490234ad0260.png)

Suggestion:
1. If name is the same, have a feedback to user to confirm Y/N if the user already exist (can make use of existing find command to help list)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: didymental/ped#8

**Comment by CommanderW324** [comment]
Intended Feature. Put in Documentation
