### ISSUE TITLE
[PE-D] Multiple people of the same name can be added if their fields are different, not sure if this is an intended feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-3/tp#148]
![image.png](https://raw.githubusercontent.com/ErnestCuong/ped/main/files/92b9cd86-c26c-452f-a13a-088dddba401f.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ErnestCuong/ped#5

**Comment by CommanderW324** [comment]
This is an intended feature.
